config/routes.rb
Rails.application.routes.draw do

  root 'posts#index'
  resources(:posts) do
    get 'index_all'
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, format: { with: VALID_EMAIL_REGEX },
    unless: Proc.new { |a| a.email.blank? }
  validates :name, :comment, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.order(:created_at => :desc).limit(10)
    @post = Post.new
    @post.name = current_post.name
    if current_post.email.present?
      @post.email = current_post.email
    end
  end

  def create
    @post = Post.new(params.require(:post).permit(:name, :email, :comment))
    if @post.save
      session[:post_id] = @post.id
      redirect_to :action => :index
    else
      @posts = Post.order(:created_at => :desc).limit(10)
      render :index
    end
  end

  def index_all
    @posts = Post.all.order(:created_at => :desc)
    render :index_all
  end

  private
  def current_post
    @_current_post ||= Post.find_by(id: session[:post_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Keijiban</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/index.html.erb
<h1>掲示板</h1>

<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <% @post.errors.full_messages.each do |err| %>
      <font color="red"><%= err %></font><br>
    <% end %>
  <% end %>

  <div>名前 : <%= f.text_field :name %></div>
  <div>e-mail : <%= f.text_field :email %></div>
  <div>コメント : <%= f.text_area :comment %></div>
  <%= f.submit %><br>
<% end %>
<hr>

<% @posts.each do |post| %>
  <%= post.id %> : <%= post.name %>
    <%= " : " + post.email if post.email.present? %> : <%= post.created_at %>
  <br>
  <pre><%= post.comment %></pre>
  <br>
<% end %>
<%= link_to '全て見る', post_index_all_path(@posts) %>

app/views/posts/index_all.html.erb
<h1>掲示板</h1>

<% @posts.each do |post| %>
  <%= post.id %> : <%= post.name %>
    <%= " : " + post.email if post.email.present? %> : <%= post.created_at %>
  <br>
  <pre><%= post.comment %></pre>
  <br>
<% end %>
<%= link_to '戻る', root_path %>